#!/usr/bin/env bash

MAIN_WORKTREE_DIR=`git worktree list | awk 'NR==1{ print $1; exit }'`
RECENT_BRANCHES_FILE=$MAIN_WORKTREE_DIR/.git/recent-branches

trimRecentBranches() {
	cat $RECENT_BRANCHES_FILE | awk 'length($0) > 0 && !seen[$0]++ && length(seen) < 21' > "${RECENT_BRANCHES_FILE}.tmp"
	mv "${RECENT_BRANCHES_FILE}.tmp" $RECENT_BRANCHES_FILE
}

addNewBranch() {
	touch $RECENT_BRANCHES_FILE
	BRANCH=`git reflog | awk 'NR==1{ print $6; exit }'`

	git show-ref --verify --quiet "refs/heads/$BRANCH"
	if [ "$?" == "0" ]; then
		echo $BRANCH | cat - $RECENT_BRANCHES_FILE > "${RECENT_BRANCHES_FILE}.tmp"
		mv "${RECENT_BRANCHES_FILE}.tmp" $RECENT_BRANCHES_FILE
		trimRecentBranches
	fi
}

if [[ "$3" = "1" ]]; then
	addNewBranch &
fi